export default {
  TRANSPORT_STARTED: "started",
  TRANSPORT_STOPPED: "stopped",
  DEFAULT_BPM_VALUE: 120,
  DEFAULT_SWING_VALUE: 0,
  DEFAULT_SWING_SUBDIVISION_VALUE: 8,
  DEFAULT_TIME_SIGNATURE_VALUE: [4, 4],
  MIN_TICKS: 0,
  MAX_TICKS: 191
};
